[mgr]

ratio = [1, 2, 1]

[plugin]
previewers = [{ url = "*/", run = "folder" }, { url = "*", run = "noop" }]

[opener]
nvim_remote = [
  { run = 'nvim --server /tmp/nvimsocket --remote "$1"', desc = "Open in existing nvim", for = "unix" },
]

[open]
prepend_rules = [{ mime = "*", use = "nvim_remote" }]
